// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcoKZrayihrJ1wC9jUcFCWa14dyuQABI',
    appId: '1:173517946754:web:b68e64cff0a19c0920599b',
    messagingSenderId: '173517946754',
    projectId: 'gohcalculator',
    authDomain: 'gohcalculator.firebaseapp.com',
    databaseURL: 'https://gohcalculator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gohcalculator.firebasestorage.app',
    measurementId: 'G-6L3MFX45JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4bTkwTKJl_ioS-Ux-FZK_jXtiUBcIbqQ',
    appId: '1:173517946754:android:417293a7ff90d60420599b',
    messagingSenderId: '173517946754',
    projectId: 'gohcalculator',
    databaseURL: 'https://gohcalculator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gohcalculator.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAupnXEkhcNuGs5m8TGMJZC56WG2NgV8KQ',
    appId: '1:173517946754:ios:e6df6ad92f4ae2e820599b',
    messagingSenderId: '173517946754',
    projectId: 'gohcalculator',
    databaseURL: 'https://gohcalculator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gohcalculator.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAupnXEkhcNuGs5m8TGMJZC56WG2NgV8KQ',
    appId: '1:173517946754:ios:e6df6ad92f4ae2e820599b',
    messagingSenderId: '173517946754',
    projectId: 'gohcalculator',
    databaseURL: 'https://gohcalculator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gohcalculator.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmcoKZrayihrJ1wC9jUcFCWa14dyuQABI',
    appId: '1:173517946754:web:97b11370175c5c4220599b',
    messagingSenderId: '173517946754',
    projectId: 'gohcalculator',
    authDomain: 'gohcalculator.firebaseapp.com',
    databaseURL: 'https://gohcalculator-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'gohcalculator.firebasestorage.app',
    measurementId: 'G-WG35RR6VBV',
  );

}